name: Update Tasks
on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  update-tasks:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      - name: Install dependencies
        run: pip install PyGithub
      
      - name: Update Tasks
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_USERNAME: ${{ github.repository_owner }}
        run: python .github/scripts/update_tasks.py
      
      - name: Commit and push
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add tasks.md
          git diff --staged --quiet || git commit -m "Update tasks.md with latest PRs [skip ci]"
          git push
